SELECT 
CASE 
    WHEN MARKS < 70 THEN 'NULL'
    ELSE NAME
END AS NAMETEXT ,
CASE 
    WHEN MARKS < 10 THEN 1
    WHEN MARKS >= 10 AND MARKS <= 19 THEN 2
    WHEN MARKS >= 20 AND MARKS <= 29 THEN 3
    WHEN MARKS >= 30 AND MARKS <= 39 THEN 4
    WHEN MARKS >= 40 AND MARKS <= 49 THEN 5
    WHEN MARKS >= 50 AND MARKS <= 59 THEN 6
    WHEN MARKS >= 60 AND MARKS <= 69 THEN 7
    WHEN MARKS >= 70 AND MARKS <= 79 THEN 8
    WHEN MARKS >= 80 AND MARKS <= 89 THEN 9
    ELSE 10
END AS MARKSTEXT, MARKS
FROM STUDENTS
ORDER BY MARKSTEXT DESC, NAME ASC